name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: newnyup319/github-actions-app
        tags: v3, latest
        registry: docker.io
        username: newnyup319
        password: dckr_pat_ntPUs_rS2Gs4DEMDExIPwhzOPJc
